github = "https://github.com/oknozor/toml-bombadil"

hooks = [
    "cargo bump %version",
    "cargo package",
    "cargo publish"
]

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
    { signature = "Dustin Speckhals", username = "DSpeckhals" },
    { signature = "Lucas Declercq", username = "lucas-dclrcq" },
]